import dotenv from 'dotenv';
dotenv.config();

export const LIKE_INTERVAL_IN_SECONDS = 15 //QUANTIDADE EM SEGUNDOS PARA EFETUAR CADA LIKE -- FORTEMENTE SUGERIDO A DEIXAR MAIOR OU IGUAL A 15
export const REPLIE_INTERVAL_IN_SECONDS = 15 //QUANTIDADE EM SEGUNDOS PARA EFETUAR CADA REPLIE -- FORTEMENTE SUGERIDO A DEIXAR MAIOR OU IGUAL A 15


export const ENABLE_REPLIES = false; // ATIVAR/DESATIVAR MENSAGENS PRONTAS (PARAMETRIZAR MENSAGENS EM src/utils/readyMadeReplies/ReadyMadeRepliesList.js)
export const ENABLE_LIKES = true; // ATIVAR/DESATIVAR LIKES

export const DETAILED_LOGS = false; // ATIVAR/DESATIVAR LOGS DETALADOS