export const badWords = [
    'abuso',
    'vadia',
    'pika',
    'foto do pau',
    'agressão',
    'anorexia',
    'assédio',
    'assédio sexual',
    'assassinato',
    'babaca',
    'cachaça',
    'corno',
    'corna',
    'capeta',
    'canalha',
    'nuds',
    'cigarro',
    'criminoso',
    'desgraçado',
    'desmoralizado',
    'escroto',
    'estúpido',
    'fetiche',
    'fraude',
    'viado',
    'viadinho',
    'putinha',
    'gore',
    'homicídio',
    'incesto',
    'insulto',
    'massacre',
    'mutilação',
    'nudez',
    'pornografia',
    'porno',
    'pornô',
    'pedofilia',
    'pedofilo',
    'pedofila',
    'putaria',
    'satanismo',
    'sequestro',
    'sexo',
    'transar',
    'transa',
    'meter',
    'metendo',
    'sexual',
    'sufocamento',
    'pintoawards',
    'pinto',
    'pau duro',
    'pau',
    'pica',
    'xereca',
    'suicídio',
    'suicidio',
    'terrorismo',
    'tortura',
    'tráfico',
    'violência sexual',
    'vulgar',
    'arrombado',
    'arrombada',
    'bosta',
    'cacete',
    'desgraçado',
    'desgraçada',
    'escroto',
    'escrota',
    'estúpido',
    'fodido',
    'fodida',
    'imbecil',
    'idiota',
    'jumento',
    'jumenta',
    'merda',
    'otário',
    'palhaço',
    'piranha',
    'puto',
    'puta',
    'recalcado',
    'safado',
    'safadinha',
    'safadinho',
    'salafrário',
    'sem vergonha',
    'vagabundo',
    'vagabunda',
    'arrombado',
    'cachaça',
    'capeta',
    'chato',
    'desmoralizado',
    'espancador',
    'punheta',
    'masturbar',
    'masturbação',
    'masturbaçao',
    'filha da puta',
    'mizerável',
    'pilantra',
    'pilantragem',
    'putaria',
    'rapariga',
    'sacana',
    'safadeza',
    'abuso infantil',
    'autoagressão',
    'bullying',
    'chantagem',
    'criminoso',
    'dopagem',
    'fraude',
    'terrorista',
    'torturador',
    'tráfico',
    'trafico',
    'sequestro',
    'opressão',
    'distúrbio',
    'fome',
    'obsessão',
    'psicose',
    'transtorno',
    'transtorno alimentar',
    'transtorno de personalidade',
    'transtorno obsessivo-compulsivo',
    'vício em drogas',
    'vício em sexo',
    'vício em videogame',
    'chantagem emocional',
    'comportamento antiético',
    'comportamento destrutivo',
    'chantagem',
    'desonestidade',
    'exploração',
    'criado-mudo',
    'crioulo',
    'escravo',
    'macumbeiro',
    'mulata',
    'samba do crioulo doido',
    'serviço de preto',
    'teta de nega',
    'pornografia extrema',
    'prostituição',
    'violação de privacidade',
  ];
  
 